version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file..
      - mvn clean install
  post_build:
    commands:
      - echo Build complete
artifacts:
  files:
    - target/gamer-shop-rest-api.jar
  discard-path: yes