services:
  backend:
    build:
      context: .
      dockerfile: /Dockerfile
    image: dvi55/game-store-back:latest
    ports:
      - "8080:8080"
    links:
      - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: QWERTY
    ports:
      - "5432:5432"